# Generated by Django 5.2.5 on 2025-09-05 15:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('zeladorx', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='typezeladoria',
            options={'managed': (False,)},
        ),
        migrations.AlterModelTable(
            name='typezeladoria',
            table='zeladorx_typezeladoria',
        ),
    ]
