# Generated by Django 5.2.5 on 2025-09-05 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresasecundario', '0001_initial'),
        ('zeladorx', '0002_alter_typezeladoria_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empresasecundaria',
            name='setor',
            field=models.ManyToManyField(to='zeladorx.typezeladoria'),
        ),
    ]
