# Generated by Django 5.2.5 on 2025-09-05 15:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attachments', '0002_alter_attachment_message'),
        ('message', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Message',
        ),
    ]
