# Generated by Django 5.2.5 on 2025-09-05 21:09

import utils.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatroom',
            name='id_random',
            field=models.CharField(default=utils.utils.generate_id_random, max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='chatroom',
            name='name',
            field=models.CharField(max_length=255),
        ),
    ]
