# Generated by Django 5.2.5 on 2025-09-02 12:49

import chat.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_alter_chatroom_options_alter_roommembership_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attachment',
            name='file',
            field=models.FileField(upload_to=chat.models.message_attachment_path, validators=[chat.models.validate_file_size]),
        ),
    ]
