# Generated by Django 5.2.5 on 2026-09-25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0004_message_is_deleted'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatroom',
            name='history_enabled',
            field=models.BooleanField(
                default=False,
                help_text='Permite que participantes consultem mensagens anteriores ao entrarem na sala.',
                verbose_name='Histórico habilitado',
            ),
        ),
    ]